kind: Deployment 
metadata: 
  name: python-deployment 
spec: 
  selector: 
    matchLabels: 
      app: python
  replicas: 2
  template:
    metadata: 
      labels: 
        app: python
    spec: 
      containers: 
      - name: python
        image: monali1307/testapp:latest
        ports: 
        - containerPort: 80 
--- 
kind: Service 
apiVersion: v1 
metadata: 
  name: python-service 
spec: 
  selector: 
    app: python
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 